import = ["/Users/makotodejima/.config/alacritty/themes/themes/blood_moon.toml"]

[colors.normal]
green = "#ADF0CD"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
style = "Regular"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[scrolling]
history = 40000

[window.dimensions]
columns = 140
lines = 100

[window.padding]
x = 2
y = 0
