import = ["/Users/makotodejima/.config/alacritty/themes/themes/blood_moon.toml"]

[colors.primary]
background = "0x0C0C0C"
foreground = "0xb3b3b3"

[colors.normal]
green = "0x459683"
yellow = "0xd6b147"
red = "0x9f342d"
blue = "0x4a7fe8"
white = "0xc4c4c4"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "Berkeley Mono"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = '\x1b[1;6A'
key = "A"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6S'
key = "S"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6D'
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6F'
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6H'
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6J'
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6K'
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6L'
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = '\x1b[1;6:'
key = ":"
mods = "Control|Shift"

[scrolling]
history = 40000

[window.dimensions]
columns = 140
lines = 100

[window.padding]
x = 0
y = 0
