tmux:
  symbols:
    branch: '⎇ '
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: '● '
    conflict: '✖ '
    modified: '✚ '
    untracked: '… '
    stashed: '⚑ '
    clean: ✔
  styles:
    clear: '#[fg=default]'
    state: '#[fg=default]'
    branch: '#[fg=default]'
    remote: '#[fg=default]'
    staged: '#[fg=green]'
    conflict: '#[fg=red]'
    modified: '#[fg=red]'
    untracked: '#[fg=default]'
    stashed: '#[fg=default]'
    clean: '#[fg=default]'
  layout: [flags, branch, divergence]
  options:
    branch_max_len: 0
