require "mkd.set"
require "mkd.keymaps"
require "mkd.compiler"
require "mkd.globals"

require "mkd.plugins"
require "mkd.plugins.cmp"
require "mkd.plugins.conform"
require "mkd.plugins.git"
require "mkd.plugins.lsp"
require "mkd.plugins.lualine"
require "mkd.plugins.telescope"
require "mkd.plugins.tree-sitter"
