return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  dependencies = {
    "nvim-treesitter/playground",
    "nvim-treesitter/nvim-treesitter-context",
  },
  config = function()
    local tree_sitter_configs = require "nvim-treesitter.configs"
    tree_sitter_configs.setup {
      ensure_installed = {
        "bash",
        "c",
        "comment",
        "cpp",
        "css",
        "diff",
        "dockerfile",
        "dot",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "graphql",
        "hcl",
        "hlsl",
        "html",
        "http",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "requirements",
        "rust",
        "scss",
        "sql",
        "terraform",
        "todotxt",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
      -- indent = {enable = true},
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
        disable = function(lang, buf)
          local count = vim.api.nvim_buf_line_count(buf)
          return count > 50000
        end,
      },
      incremental_selection = {
        enable = true,
        keymaps = { node_incremental = "ni", node_decremental = "nd" },
      },
    }
  end,
}
